// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/Adcols/gin-server-api/config"
	"github.com/Adcols/gin-server-api/internal/repo"
	"github.com/Adcols/gin-server-api/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeUserService 初始化用户服务
func InitializeUserService() *service.UserService {
	db := ProvideDB()
	userRepo := ProvideUserRepo(db)
	userService := ProvideUserService(userRepo)
	return userService
}

// wire.go:

// ProvideDB 提供数据库实例
func ProvideDB() *gorm.DB {
	return config.DB
}

// ProvideUserRepo 提供用户仓库实例
func ProvideUserRepo(db *gorm.DB) *repo.UserRepo {
	return repo.NewUserRepo(db)
}

// ProvideUserService 提供用户服务实例
func ProvideUserService(userRepo *repo.UserRepo) *service.UserService {
	return &service.UserService{UserRepo: userRepo}
}
