// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID        uint32         `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:用户ID" json:"id"`                       // 用户ID
	Username  string         `gorm:"column:username;type:varchar(50);not null;uniqueIndex:username,priority:1;comment:用户名" json:"username"`  // 用户名
	Email     string         `gorm:"column:email;type:varchar(100);not null;uniqueIndex:email,priority:1;comment:邮箱" json:"email"`           // 邮箱
	Password  string         `gorm:"column:password;type:varchar(100);not null;comment:密码" json:"password"`                                  // 密码
	Avatar    string         `gorm:"column:avatar;type:varchar(200);not null;comment:头像" json:"avatar"`                                      // 头像
	Nickname  string         `gorm:"column:nickname;type:varchar(50);not null;comment:昵称" json:"nickname"`                                   // 昵称
	Gender    uint32         `gorm:"column:gender;type:tinyint unsigned;not null;comment:性别（0.未知 1.男 2.女）" json:"gender"`                    // 性别（0.未知 1.男 2.女）
	Phone     *string        `gorm:"column:phone;type:varchar(11);comment:手机号" json:"phone"`                                                 // 手机号
	Status    uint32         `gorm:"column:status;type:tinyint unsigned;not null;comment:状态（1.正常 2.冻结）" json:"status"`                       // 状态（1.正常 2.冻结）
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`      // 创建时间
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`      // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_user_deleted_at,priority:1;comment:删除时间" json:"deleted_at"` // 删除时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
